-- AlterTable
ALTER TABLE "Documento" ALTER COLUMN "DataDocumento" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "PathArquivoPDF" SET DATA TYPE VARCHAR(255);

-- AlterTable
ALTER TABLE "Tramitacao" ALTER COLUMN "DataHoraEnvio" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "DataHoraRecebe" DROP NOT NULL;
